POST {{VehiclePriceCalculator_HostAddress}}/api/pricecalculator/calculate
Content-Type: application/json

{
"baseNet": 10000,
"baseGross": null,
"equipmentNet": 100,
"equipmentGross": null,
"vatRate": 0.22
}