@VehiclePriceCalculator_HostAddress = http://localhost:5137

POST {{VehiclePriceCalculator_HostAddress}}/api/pricecalculator/calculate
Content-Type: application/json

{
"baseNet": 0,
"baseGross": 3344,
"equipmentNet": 1,
"equipmentGross": null,
"vatRate": 22.00
}